openeuropa/oe_paragraphs

- composer.json
- config/install/core.entity_form_display.paragraph.oe_accordion.default.yml
- config/install/core.entity_form_display.paragraph.oe_accordion_item.default.yml
- config/install/core.entity_view_display.paragraph.oe_accordion.default.yml
- config/install/core.entity_view_display.paragraph.oe_accordion_item.default.yml
- config/install/field.field.paragraph.oe_accordion.field_oe_paragraphs.yml
- config/install/field.field.paragraph.oe_accordion_item.field_oe_icon.yml
- config/install/field.field.paragraph.oe_accordion_item.field_oe_text.yml
- config/install/field.field.paragraph.oe_accordion_item.field_oe_text_long.yml
- config/install/field.storage.paragraph.field_oe_icon.yml
- config/install/field.storage.paragraph.field_oe_paragraphs.yml
- config/install/paragraphs.paragraphs_type.oe_accordion.yml
- config/install/paragraphs.paragraphs_type.oe_accordion_item.yml
- oe_paragraphs.info.yml
- oe_paragraphs_demo/config/install/field.field.node.oe_demo_landing_page.field_oe_demo_body.yml
- tests/features/create-landing-page.feature
- Created Accordion item
- Created accordion paragrapfs
- Re-use existing fields for title and body
- Created Icon field, which it is a select field with list of ECL icons reference name
- Attached a According paragraph type to the body of demo_landing_page content type
- TBD the behat test (WIP)
>   OPENEUROPA-307: Accordion paragraph.

- composer.json
- config/install/core.entity_form_display.paragraph.oe_quote.default.yml
- config/install/core.entity_view_display.paragraph.oe_quote.default.yml
- config/install/field.field.paragraph.oe_quote.field_oe_text.yml
- config/install/field.field.paragraph.oe_quote.field_oe_text_long.yml
- config/install/paragraphs.paragraphs_type.oe_accordion.yml
- config/install/paragraphs.paragraphs_type.oe_quote.yml
- oe_paragraphs.info.yml
- oe_paragraphs_demo/config/install/field.field.node.oe_demo_landing_page.field_oe_demo_body.yml
- tests/features/create-landing-page.feature
- Created Quote paragraph type
- Attached two existing field to quote
- Update behat test
- Attached Quote paragraph to the oe_paragraphs_demo_landing_page content type
>   OPENEUROPA-308: Quote paragraph

- config/install/field.field.paragraph.oe_links_block.field_oe_links.yml
- config/install/field.field.paragraph.oe_links_block.field_oe_text.yml
- config/install/field.field.paragraph.oe_rich_text.field_oe_text_long.yml
- config/optional/language.content_settings.paragraph.oe_accordion.yml
- config/optional/language.content_settings.paragraph.oe_accordion_item.yml
- config/optional/language.content_settings.paragraph.oe_links_block.yml
- config/optional/language.content_settings.paragraph.oe_quote.yml
- config/optional/language.content_settings.paragraph.oe_rich_text.yml
- oe_paragraphs.info.yml
- oe_paragraphs_demo/config/install/core.entity_form_display.node.oe_demo_landing_page.default.yml
- oe_paragraphs_demo/config/install/core.entity_view_display.node.oe_demo_landing_page.default.yml
- oe_paragraphs_demo/config/install/core.entity_view_display.node.oe_demo_landing_page.teaser.yml
- oe_paragraphs_demo/config/optional/language.content_settings.node.oe_demo_landing_page.yml
- oe_paragraphs_demo/oe_paragraphs_demo.info.yml
Add multilingual configuration to existing paragraphs
- Added: Add multilingual configuration to existing paragraphs
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
> OPENEUROPA-559

- .github/pull_request_template.md
- composer.json
Add openeuropa/drupal-core-require-dev on composer.json.
- Added: openeuropa/drupal-core-require-dev on composer.json.
- Removed: webflo/drupal-core-require-dev on composer.json.
```sh
composer update
```
> OPENEUROPA-772: Add openeuropa/drupal-core-require-dev on composer.json.

- CHANGELOG.md
> Update Changelog for upcoming release 0.3.0.

- .drone.yml
- composer.json
> OPENEUROPA-1533: Add --strict flag for Behat tests executions.

- config/install/core.entity_form_display.paragraph.oe_contextual_navigation.default.yml
- config/install/core.entity_view_display.paragraph.oe_contextual_navigation.default.yml
- config/install/field.field.paragraph.oe_contextual_navigation.field_oe_limit.yml
- config/install/field.field.paragraph.oe_contextual_navigation.field_oe_links.yml
- config/install/field.field.paragraph.oe_contextual_navigation.field_oe_text.yml
- config/install/field.field.paragraph.oe_contextual_navigation.field_oe_title.yml
- config/install/field.storage.paragraph.field_oe_limit.yml
- config/install/paragraphs.paragraphs_type.oe_contextual_navigation.yml
- config/optional/language.content_settings.paragraph.oe_contextual_navigation.yml
- modules/oe_paragraphs_demo/config/install/field.field.node.oe_demo_landing_page.field_oe_demo_body.yml
- tests/features/create-landing-page.feature
- tests/features/variants.feature
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-1803: Create new Contextual navigation paragraph type.

- behat.yml.dist
- composer.json
- modules/oe_paragraphs_demo/config/install/user.role.editor.yml
- src/Plugin/Field/FieldWidget/ParagraphVariantsWidget.php
- tests/Behat/ParagraphsContext.php
- tests/features/variants.feature
Paragraph variant doesn't stay selected when resaving the content.
> OPENEUROPA-1843: Paragraph variant doesn't stay selected when resaving the content

- CHANGELOG.md
Create release 0.6.0.
- Added:
- Changed: Changelog.md
- Deprecated:
- Removed:
- Fixed:
- Security:
> OPENEUROPA-1813: Create release 0.6.0.

- .drone.yml
- composer.json
- src/Plugin/Field/FieldWidget/ParagraphVariantsWidget.php
Updating the method from paragraphs config with the latest changes.
> OPENEUROPA-1885: Update method to paragraphs commit: 0fafd516.

- config/install/field.field.paragraph.oe_contextual_navigation.field_oe_limit.yml
- oe_paragraphs.install
- oe_paragraphs.post_update.php
Fix limit field description
- Added:
- Changed: Fix limit field description
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-1862: Fix description for limit field.

- README.md
Update README documentation.
- Added: Paragraphs documentation
> OPENEUROPA-0000: Update paragraphs README documentation.

- behat.yml.dist
- composer.json
- modules/oe_paragraphs_demo/config/install/field.field.node.oe_demo_landing_page.field_oe_demo_body.yml
- modules/oe_paragraphs_demo/config/install/user.role.editor.yml
- modules/oe_paragraphs_demo/oe_paragraphs_demo.info.yml
- modules/oe_paragraphs_map/README.md
- modules/oe_paragraphs_map/config/install/core.entity_form_display.paragraph.oe_map.default.yml
- modules/oe_paragraphs_map/config/install/core.entity_view_display.paragraph.oe_map.default.yml
- modules/oe_paragraphs_map/config/install/field.field.paragraph.oe_map.field_oe_media.yml
- modules/oe_paragraphs_map/config/install/paragraphs.paragraphs_type.oe_map.yml
- modules/oe_paragraphs_map/oe_paragraphs_map.info.yml
- tests/features/create-landing-page.feature
- tests/features/map.feature
Scope of the ticket is to create a new module called oe_paragraphs_map, with a dependency on oe_paragraphs_media_field_storage module, which will create a new paragraph that allows to reference a map media.
> OPENEUROPA-2974: [oe_paragraphs] Map paragraph.

- behat.yml.dist
- composer.json
- modules/oe_paragraphs_demo/config/install/field.field.node.oe_demo_landing_page.field_oe_demo_body.yml
- modules/oe_paragraphs_demo/config/install/user.role.editor.yml
- modules/oe_paragraphs_demo/oe_paragraphs_demo.info.yml
- modules/oe_paragraphs_social_feed/README.md
- modules/oe_paragraphs_social_feed/config/install/core.entity_form_display.paragraph.oe_social_feed.default.yml
- modules/oe_paragraphs_social_feed/config/install/core.entity_view_display.paragraph.oe_social_feed.default.yml
- modules/oe_paragraphs_social_feed/config/install/field.field.paragraph.oe_social_feed.field_oe_media.yml
- modules/oe_paragraphs_social_feed/config/install/paragraphs.paragraphs_type.oe_social_feed.yml
- modules/oe_paragraphs_social_feed/oe_paragraphs_social_feed.info.yml
- tests/features/create-landing-page.feature
- tests/features/social-feed.feature
Add Social feed paragraph.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-2996: Add Social feed paragraph.

- composer.json
> OPENEUROPA-3159: Re-rolled paragraphs widget patch.

- CHANGELOG.md
Prepare release 1.6.0.
- Added:
- Changed: Update changelog for 1.6.0.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> Prepare release 1.6.0.

- .gitignore
- composer.json
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-529: Replace scaffold library.

- tests/features/chart.feature
- tests/features/map.feature
- tests/features/social-feed.feature
- tests/features/timeline.feature
Quick fix behat tests resulting from latest oe_content release.
- Added: Quick fix behat tests resulting from latest oe_content release.
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-858: Quickfix behat tests.

- .drone.yml
- README.md
- composer.json
- runner.yml.dist
- tests/features/timeline.feature
Revert quickfix introduced on EWPP-858
- Added:
- Changed: Revert quickfix introduced on EWPP-858
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-974: Revert quickfix.

- modules/oe_paragraphs_media/config/post_updates/00003_update_view_display/core.entity_view_display.paragraph.oe_text_feature_media.default.yml
- modules/oe_paragraphs_media/oe_paragraphs_media.post_update.php
https://github.com/openeuropa/oe_theme/pull/878/files#diff-6ea785e6d300fd84ad57e5df27d3d4a2a5f182558df3883edde91fd1648a4a4bR303 move here
> EWPP-873: Move update from oe_theme to oe_paragraphs

- CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-0000: Prepare for 1.11.0 release.

- CHANGELOG.md
Prepare release 1.12.0.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> Prepare release 1.12.0.

- composer.json
- modules/oe_paragraphs_contact/config/install/field.field.paragraph.oe_contact.field_oe_contacts.yml
- modules/oe_paragraphs_contact/oe_paragraphs_contact.post_update.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-2106: Update Carousel epic branch.

- modules/oe_paragraphs_carousel/config/install/core.entity_form_display.paragraph.oe_carousel_item.default.yml
- modules/oe_paragraphs_carousel/config/install/core.entity_view_display.paragraph.oe_carousel_item.default.yml
- modules/oe_paragraphs_carousel/config/install/field.field.paragraph.oe_carousel_item.field_oe_text.yml
- modules/oe_paragraphs_carousel/oe_paragraphs_carousel.info.yml
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-2278: Replace type of Description field to field_oe_text.

- CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> Prepare release 1.13.1.

- composer.json
- config/install/field.storage.paragraph.field_oe_social_media_links.yml
- oe_paragraphs.post_update.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-2106: Update branch for Carousel epic.

- CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> Prepare release 1.15.0.

- CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> Prepare release 1.16.0.

- .drone.yml
- tests/Behat/ParagraphsContext.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OEL-3046: Update to Drupal 10.3

- composer.json
https://www.drupal.org/project/paragraphs/issues/2890086#comment-15719614
> EWPP-4602: Reroll paragraphs patch for form validation.

- .drone.yml
- docker-compose.yml
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-5461: Update sparql image in docker-compose.yml and for drone.yml.

- .drone.yml
- behat.yml.dist
- composer.json
- modules/oe_paragraphs_av_media/oe_paragraphs_av_media.info.yml
- modules/oe_paragraphs_banner/oe_paragraphs_banner.info.yml
- modules/oe_paragraphs_carousel/oe_paragraphs_carousel.info.yml
- modules/oe_paragraphs_chart/oe_paragraphs_chart.info.yml
- modules/oe_paragraphs_contact/oe_paragraphs_contact.info.yml
- modules/oe_paragraphs_demo/oe_paragraphs_demo.info.yml
- modules/oe_paragraphs_description_list/oe_paragraphs_description_list.info.yml
- modules/oe_paragraphs_document/oe_paragraphs_document.info.yml
- modules/oe_paragraphs_gallery/oe_paragraphs_gallery.info.yml
- modules/oe_paragraphs_iframe_media/oe_paragraphs_iframe_media.info.yml
- modules/oe_paragraphs_illustrations_lists/oe_paragraphs_illustrations_lists.info.yml
- modules/oe_paragraphs_illustrations_lists/tests/modules/oe_paragraphs_illustrations_lists_test/oe_paragraphs_illustrations_lists_test.info.yml
- modules/oe_paragraphs_map/oe_paragraphs_map.info.yml
- modules/oe_paragraphs_media/oe_paragraphs_media.info.yml
- modules/oe_paragraphs_media_field_storage/oe_paragraphs_media_field_storage.info.yml
- modules/oe_paragraphs_social_feed/oe_paragraphs_social_feed.info.yml
- modules/oe_paragraphs_timeline/oe_paragraphs_timeline.info.yml
- oe_paragraphs.info.yml
- phpunit.xml.dist
- runner.yml.dist
- tests/features/document.feature
- tests/features/timeline.feature
- tests/modules/oe_paragraphs_options_event_test/oe_paragraphs_options_event_test.info.yml
Add Drupal 11 support.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
> EWPP-4643: Update to Drupal 11.

- .drone.yml
- docker-compose.yml
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-5553: Update sparql image in docker-compose.yml and .drone.yml.

- modules/oe_paragraphs_description_list/config/install/field.field.paragraph.oe_description_list.field_oe_title.yml
- oe_paragraphs.post_update.php
- tests/features/description-list.feature
Make the description list heading optional.
> EWPP-5662: Make the description list heading optional.

- composer.json
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-5655: Remove allowed_formats from composer.json.
